# -*- coding: utf-8 -*-
"""Homework4Evaluate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zrwtZVtMCy3nJlhevjWtjrojkzPvhbn
"""

import numpy as np
import tensorflow as tf
from google.colab import drive

# Define constants
IMAGE_SIZE = 96
BATCH_SIZE = 32
BASE_DIR = '/content/drive/My Drive/ML/Dog_Images'  # Update this with the actual path
validation_split = 0.9  # Adjust the validation split if needed

# Load the trained model
model = tf.keras.models.load_model('/content/drive/My Drive/ML/dog_recognition.h5')

# Define data generators for validation
datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1. / 255,
    validation_split=validation_split
)

val_generator = datagen.flow_from_directory(
    BASE_DIR,
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    subset='validation',
    color_mode='grayscale'
)

# Evaluate the model
evaluation = model.evaluate(val_generator)
print("Validation Loss:", evaluation[0])
print("Validation Accuracy:", evaluation[1])